import { useState } from 'react';
import ExportButton from '../ui/ExportButton';

export default function ActionBar() {
  const [copied, setCopied] = useState(false);

  const copySummary = async () => {
    const text = `Financial Research Report — Generated by Finora`;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      /* clipboard unavailable — still show feedback */
    }
    setCopied(true);
    window.setTimeout(() => setCopied(false), 2400);
  };

  const verifySources = () => {
    window.dispatchEvent(new CustomEvent('finora:goto-tab', { detail: 'sources' }));
  };

  return (
    <div className="flex flex-wrap items-center gap-3">
      <ExportButton label="Download PDF" />

      <button
        type="button"
        onClick={verifySources}
        className="btn-press inline-flex h-9 items-center gap-2 rounded-sm border border-hairline bg-canvas px-3.5 text-button-md text-ink hover:border-hairline-strong"
      >
        <svg width="13" height="13" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <path
            d="M8 1.8l5.2 2v4.1c0 3.2-2.2 5.3-5.2 6.3-3-1-5.2-3.1-5.2-6.3V3.8L8 1.8z"
            stroke="currentColor"
            strokeWidth="1.4"
            strokeLinejoin="round"
          />
          <path d="M5.8 8l1.6 1.6 2.8-3.2" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
        Verify Sources
      </button>

      <button
        type="button"
        onClick={copySummary}
        className={
          'btn-press inline-flex h-9 items-center gap-2 rounded-sm border px-3.5 text-button-md ' +
          (copied ? 'border-up/40 bg-up/10 text-up' : 'border-hairline bg-canvas text-ink hover:border-hairline-strong')
        }
      >
        {copied ? (
          <svg width="13" height="13" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path d="M3 8.5l3.5 3.5L13 4.5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        ) : (
          <svg width="13" height="13" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <rect x="4.5" y="4.5" width="8" height="8" rx="1" stroke="currentColor" strokeWidth="1.3" />
            <path d="M6 4.5V3.8A1.3 1.3 0 0 1 7.3 2.5h4.9A1.3 1.3 0 0 1 13.5 3.8v4.9a1.3 1.3 0 0 1-1.3 1.3h-0.7" stroke="currentColor" strokeWidth="1.3" />
          </svg>
        )}
        {copied ? 'Copied' : 'Copy Summary'}
      </button>

      <a
        href="/chat"
        className="btn-press inline-flex h-9 items-center gap-2 rounded-sm bg-ink px-3.5 text-button-md text-canvas hover:opacity-90"
      >
        <svg width="13" height="13" viewBox="0 0 18 18" fill="none" aria-hidden="true">
          <path d="M3.5 2.5h11a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7.5L4 15.5v-3H3.5a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" />
        </svg>
        Ask Questions
      </a>
    </div>
  );
}
