"""Metric methodology documentation.

Defines the formula, required inputs, and handling rules for every
calculated financial metric in Finora.  This serves as both the
authoritative reference for the calculation engine and the future
source for the verification modal / public methodology page.
"""

METODOLOGY: dict[str, dict] = {
    # ── Growth ────────────────────────────────────────────────────────────
    "revenue_growth": {"name": "Revenue Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(Revenue_current - Revenue_previous) / Revenue_previous * 100",
        "notes": "Compares two consecutive annual periods."},
    "gross_profit_growth": {"name": "Gross Profit Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(GrossProfit_current - GrossProfit_previous) / GrossProfit_previous * 100",
        "notes": "Year-over-year change in gross profit."},
    "operating_income_growth": {"name": "Operating Income Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(OpIncome_current - OpIncome_previous) / OpIncome_previous * 100",
        "notes": "Year-over-year change in operating income."},
    "net_income_growth": {"name": "Net Income Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(NetIncome_current - NetIncome_previous) / NetIncome_previous * 100",
        "notes": "Year-over-year change in net income."},
    "eps_growth": {"name": "EPS Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(EPS_current - EPS_previous) / EPS_previous * 100",
        "notes": "Uses diluted EPS."},
    "ocf_growth": {"name": "Operating Cash Flow Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(OCF_current - OCF_previous) / OCF_previous * 100",
        "notes": "Year-over-year change in operating cash flow."},
    "fcf_growth": {"name": "Free Cash Flow Growth (YoY)", "unit": "%", "classification": "calculated",
        "formula": "(FCF_current - FCF_previous) / FCF_previous * 100",
        "notes": "Calculated from operating cash flow growth proxy."},
    "revenue_cagr": {"name": "Revenue CAGR", "unit": "%", "classification": "calculated",
        "formula": "(Revenue_end / Revenue_start)^(1/n) - 1",
        "notes": "Requires at least 2 years of data."},
    "net_income_cagr": {"name": "Net Income CAGR", "unit": "%", "classification": "calculated",
        "formula": "(NetIncome_end / NetIncome_start)^(1/n) - 1",
        "notes": "Compound annual growth rate of net income."},
    "eps_cagr": {"name": "EPS CAGR", "unit": "%", "classification": "calculated",
        "formula": "(EPS_end / EPS_start)^(1/n) - 1",
        "notes": "Compound annual growth rate of diluted EPS."},

    # ── Profitability ─────────────────────────────────────────────────────
    "gross_margin": {"name": "Gross Margin", "unit": "%", "classification": "calculated",
        "formula": "Gross Profit / Revenue * 100",
        "notes": "Proportion of revenue retained after cost of goods sold."},
    "operating_margin": {"name": "Operating Margin", "unit": "%", "classification": "calculated",
        "formula": "Operating Income / Revenue * 100",
        "notes": "Proportion of revenue retained after all operating expenses."},
    "pretax_margin": {"name": "Pretax Margin", "unit": "%", "classification": "calculated",
        "formula": "Pretax Income / Revenue * 100",
        "notes": "Profitability before income taxes."},
    "net_margin": {"name": "Net Profit Margin", "unit": "%", "classification": "calculated",
        "formula": "Net Income / Revenue * 100",
        "notes": "Bottom-line profitability per dollar of revenue."},
    "ebitda_margin": {"name": "EBITDA Margin", "unit": "%", "classification": "calculated",
        "formula": "EBITDA / Revenue * 100",
        "notes": "Only available when EBITDA can be derived."},
    "fcf_margin": {"name": "Free Cash Flow Margin", "unit": "%", "classification": "calculated",
        "formula": "Free Cash Flow / Revenue * 100",
        "notes": "Cash generation efficiency relative to revenue."},
    "ocf_margin": {"name": "Operating Cash Flow Margin", "unit": "%", "classification": "calculated",
        "formula": "Operating Cash Flow / Revenue * 100",
        "notes": ""},

    # ── Returns ───────────────────────────────────────────────────────────
    "roa": {"name": "Return on Assets", "unit": "%", "classification": "calculated",
        "formula": "Net Income / Average Total Assets * 100",
        "notes": "Falls back to ending balance if prior year unavailable."},
    "roe": {"name": "Return on Equity", "unit": "%", "classification": "calculated",
        "formula": "Net Income / Average Stockholders' Equity * 100",
        "notes": "Falls back to ending balance if prior year unavailable."},
    "roic": {"name": "Return on Invested Capital", "unit": "%", "classification": "calculated",
        "formula": "NOPAT / Invested Capital * 100",
        "notes": "Uses effective tax rate if available, else 21% default. IC = Debt + Equity - Cash."},
    "roce": {"name": "Return on Capital Employed", "unit": "%", "classification": "calculated",
        "formula": "NOPAT / Capital Employed * 100, where Capital Employed = Total Assets - Current Liabilities",
        "notes": "Uses effective tax rate if available."},

    # ── Cash Flow ─────────────────────────────────────────────────────────
    "free_cash_flow": {"name": "Free Cash Flow", "unit": "USD", "classification": "calculated",
        "formula": "Operating Cash Flow - Capital Expenditures",
        "notes": "CapEx is treated as positive (absolute value). SEC data may report as negative."},
    "cash_conversion": {"name": "Cash Conversion (FCF/Net Income)", "unit": "%", "classification": "calculated",
        "formula": "Free Cash Flow / Net Income * 100",
        "notes": "Measures how much of reported earnings convert to free cash flow."},
    "ocf_to_net_income": {"name": "OCF / Net Income", "unit": "%", "classification": "calculated",
        "formula": "Operating Cash Flow / Net Income * 100",
        "notes": "Measures cash generation quality relative to reported earnings."},
    "capex_intensity": {"name": "CapEx Intensity", "unit": "%", "classification": "calculated",
        "formula": "Capital Expenditures / Revenue * 100",
        "notes": ""},
    "capex_to_ocf": {"name": "CapEx / OCF", "unit": "%", "classification": "calculated",
        "formula": "Capital Expenditures / Operating Cash Flow * 100",
        "notes": ""},
    "cash_flow_to_debt": {"name": "Cash Flow to Debt", "unit": "%", "classification": "calculated",
        "formula": "Operating Cash Flow / Total Debt * 100",
        "notes": ""},

    # ── Liquidity ─────────────────────────────────────────────────────────
    "current_ratio": {"name": "Current Ratio", "unit": "x", "classification": "calculated",
        "formula": "Current Assets / Current Liabilities",
        "notes": ""},
    "quick_ratio": {"name": "Quick Ratio", "unit": "x", "classification": "calculated",
        "formula": "(Cash + ST Investments + Accounts Receivable) / Current Liabilities",
        "notes": ""},
    "cash_ratio": {"name": "Cash Ratio", "unit": "x", "classification": "calculated",
        "formula": "(Cash + ST Investments) / Current Liabilities",
        "notes": "Most conservative liquidity ratio."},
    "net_working_capital": {"name": "Net Working Capital", "unit": "USD", "classification": "calculated",
        "formula": "Current Assets - Current Liabilities",
        "notes": ""},
    "nwc_to_revenue": {"name": "Net Working Capital / Revenue", "unit": "%", "classification": "calculated",
        "formula": "Net Working Capital / Revenue * 100",
        "notes": ""},

    # ── Leverage ──────────────────────────────────────────────────────────
    "debt_to_equity": {"name": "Debt / Equity", "unit": "x", "classification": "calculated",
        "formula": "Total Liabilities / Stockholders' Equity",
        "notes": "Uses total liabilities as total debt proxy."},
    "debt_to_assets": {"name": "Debt / Assets", "unit": "x", "classification": "calculated",
        "formula": "Total Liabilities / Total Assets",
        "notes": ""},
    "debt_to_capital": {"name": "Debt / Capital", "unit": "%", "classification": "calculated",
        "formula": "Total Debt / (Total Debt + Equity) * 100",
        "notes": "Total Debt = Short-term + Long-term debt."},
    "net_debt": {"name": "Net Debt", "unit": "USD", "classification": "calculated",
        "formula": "Total Debt - Cash - ST Investments",
        "notes": "Negative means company has more cash than debt."},
    "debt_to_ebitda": {"name": "Debt / EBITDA", "unit": "x", "classification": "calculated",
        "formula": "Total Debt / EBITDA",
        "notes": "Only when EBITDA derivable."},
    "net_debt_to_ebitda": {"name": "Net Debt / EBITDA", "unit": "x", "classification": "calculated",
        "formula": "Net Debt / EBITDA",
        "notes": "Only when EBITDA derivable."},
    "interest_coverage": {"name": "Interest Coverage", "unit": "x", "classification": "calculated",
        "formula": "Operating Income / Interest Expense",
        "notes": "Interest expense not always available in XBRL."},

    # ── Efficiency ────────────────────────────────────────────────────────
    "asset_turnover": {"name": "Asset Turnover", "unit": "x", "classification": "calculated",
        "formula": "Revenue / Total Assets",
        "notes": "Measures asset utilization efficiency."},
    "receivables_turnover": {"name": "Receivables Turnover", "unit": "x", "classification": "calculated",
        "formula": "Revenue / Accounts Receivable",
        "notes": "How quickly receivables are collected."},
    "inventory_turnover": {"name": "Inventory Turnover", "unit": "x", "classification": "calculated",
        "formula": "Cost of Revenue / Inventory",
        "notes": "Not meaningful for service companies without inventory."},
    "days_sales_outstanding": {"name": "Days Sales Outstanding", "unit": "days", "classification": "calculated",
        "formula": "365 / Receivables Turnover",
        "notes": ""},
    "days_inventory_outstanding": {"name": "Days Inventory Outstanding", "unit": "days", "classification": "calculated",
        "formula": "365 / Inventory Turnover",
        "notes": ""},
    "days_payable_outstanding": {"name": "Days Payable Outstanding", "unit": "days", "classification": "calculated",
        "formula": "365 / Payables Turnover",
        "notes": "Uses Cost of Revenue / Accounts Payable."},
    "cash_conversion_cycle": {"name": "Cash Conversion Cycle", "unit": "days", "classification": "calculated",
        "formula": "DSO + DIO - DPO",
        "notes": "Measures cash conversion efficiency."},

    # ── Per Share ─────────────────────────────────────────────────────────
    "revenue_per_share": {"name": "Revenue per Share", "unit": "USD", "classification": "calculated",
        "formula": "Revenue / Diluted Shares Outstanding",
        "notes": "Revenue attributable to each share on a diluted basis."},
    "fcf_per_share": {"name": "Free Cash Flow per Share", "unit": "USD", "classification": "calculated",
        "formula": "Free Cash Flow / Diluted Shares Outstanding",
        "notes": "Free cash flow attributable to each share."},
    "book_value_per_share": {"name": "Book Value per Share", "unit": "USD", "classification": "calculated",
        "formula": "Stockholders' Equity / Diluted Shares Outstanding",
        "notes": "Equity attributable to each share."},

    # ── Capital Allocation ────────────────────────────────────────────────
    "dividend_payout_ratio": {"name": "Dividend Payout Ratio", "unit": "%", "classification": "calculated",
        "formula": "Dividends Paid / Net Income * 100",
        "notes": ""},
    "buyback_to_fcf": {"name": "Buyback / FCF", "unit": "%", "classification": "calculated",
        "formula": "Share Repurchases / Free Cash Flow * 100",
        "notes": ""},
    "effective_tax_rate": {"name": "Effective Tax Rate", "unit": "%", "classification": "derived",
        "formula": "Income Tax Expense / Pretax Income * 100",
        "notes": "Derived from SEC financial data."},

    # ── EBITDA ────────────────────────────────────────────────────────────
    "ebitda": {"name": "Derived EBITDA", "unit": "USD", "classification": "derived",
        "formula": "Operating Income + Depreciation & Amortization",
        "notes": "Clearly labeled as Derived. D&A not always available."},

    # ── DuPont ────────────────────────────────────────────────────────────
    "dupont": {"name": "DuPont ROE Decomposition", "unit": "%", "classification": "calculated",
        "formula": "Net Margin x Asset Turnover x Equity Multiplier",
        "notes": "Decomposes ROE into profitability, efficiency, and leverage components."},
}
